# Generated by Django 4.2.15 on 2024-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phisher', '0002_signin_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='client_ip',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='signin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
