# Generated by Django 4.2.15 on 2024-09-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phisher', '0003_signin_client_ip_alter_signin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='password',
        ),
        migrations.AddField(
            model_name='signin',
            name='feedback_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='feedback_warning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='password_strength',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
