# Generated by Django 4.2.15 on 2024-09-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phisher', '0006_rename_crack_time_display_signin_crack_time_display_offline_fast_hashing_10_milliards_per_second_and'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='guesses',
            field=models.IntegerField(),
        ),
    ]
