# Generated by Django 4.2.15 on 2024-09-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phisher', '0007_alter_signin_guesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='sequence_l33t',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='sequence_pattern',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='sequence_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='sequence_reversed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
