# Generated by Django 4.2.15 on 2024-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phisher', '0008_signin_sequence_l33t_signin_sequence_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signin',
            name='nbr_lower',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signin',
            name='nbr_nbr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signin',
            name='nbr_special',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signin',
            name='nbr_upper',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
